default: &default
  adapter: postgres
  host: localhost
  user: tabster
  password: retsbat321!

development:
  <<: *default
  db: tabster_development

test:
  <<: *default
  db: tabster_test

production:
  adapter: postgres
  encoding: utf8
  pool: 15
